### model
model_name_or_path: /app/models/Qwen2.5-0.5B-Instruct
trust_remote_code: true

### method
stage: pt
do_train: true
finetuning_type: full
deepspeed: /app/qwen2-fope/ds_config_qwen2_fope.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: fineweb, fineweb_edu
template: qwen
cutoff_len: 8192
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: /app/saves/qwen2-0.5b-fope/full/ct
logging_steps: 25
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 32
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### FoPE Runtime Configuration (following VideoRope pattern)
which_rope: fope
fourier_learnable: true
fourier_init: eye_xavier_norm
fourier_dim: 0
fourier_init_norm_gain: 0.3
fourier_separate_basis: true
fourier_separate_head: true
fourier_norm: false
fourier_ignore_zero: true
